### ISSUE TITLE
Q: Alternatives to polling last+1 block

### ISSUE THREAD

**Issue by jsarenik** [lightningamp/esplora_clnd_plugin#50]
My `bitcoind -testnet` replies to `bitcoin-cli -testnet getblockheight` with `1969804` but `lightningd` with `esplora_clnd_plugin` repeatedly tries to get block `1969805`. Are there other options than polling `last+1` block repeatedly? (/me thinks about `bitcoind` message `Synchronizing blockheaders, height: 1969804 (~100.00%)`)

Just wondering, maybe it is not worth the time but here it is, waiting for ideas.

**Comment by lvaccaro** [comment]
Hi @jsarenik , the plugin uses only stateless http request to esplora. 
If you want to remove the polling, I thing you need something like websocket or queue to wait new block notification. Another step could be to cache block locally when they are notified.
What do you think?

**Comment by jsarenik** [comment]
Hi @lvaccaro, I am thinking of a hybrid `bcli-esplora` that also connects to a locally run (often pruned) `bitcoind` and downloads from esplora only those blocks which are not present locally. No clear idea yet, letting it to develop unconsciously first…

**Comment by lvaccaro** [comment]
do you think about a plugin or an external tool that simulate bitcoin core output?
if second choice, it sounds like https://github.com/gdassori/spruned .

**Comment by jsarenik** [comment]
After all consideration I think that the stateless http requests to esplora are the best option. Closing this issue.
